import type { Persona } from "@/lib/persona-studio/ai/schemas/persona";
import type { PersonaSection } from "@/lib/persona-studio/ai/schemas/section";
import type { PersonaStatement } from "@/lib/persona-studio/ai/schemas/statement";
import type {
  BehaviouralCluster,
  ClusterSet,
  GenerationMeta,
  SourceAnalysisResult,
  SourceInsight,
} from "@/lib/persona-studio/ai/schemas/analysis";
import type { PersonaAuditResult } from "@/lib/persona-studio/ai/schemas/chat";
import { PROMPT_VERSION } from "@/lib/persona-studio/ai/prompts";
import { reviewPersona } from "@/lib/persona-studio/utils/review";
import { scaffoldPersona } from "@/lib/persona-studio/utils/persona-factory";
import type {
  AnalyseSourcesInput,
  GenerateClustersInput,
  GeneratePersonaInput,
  PersonaAiService,
} from "./types";

/**
 * Deterministic, clearly-labelled MOCK AI service for Phase 2.
 *
 * It does NOT call any model. It produces structured, schema-valid output from
 * a fixed catalogue of behavioural patterns so the create wizard is fully
 * demonstrable offline. Crucially, it respects every grounding rule:
 *  - nothing it emits is tagged EVIDENCE (drafts are ASSUMPTION / TO_VALIDATE),
 *  - quotes are DRAFTED_HYPOTHESIS,
 *  - generated confidence is LOW,
 *  - the `meta.disclaimer` makes clear the content is machine-drafted, not
 *    research.
 *
 * Phase 3/5 swaps this for an OpenAI-backed implementation behind the same
 * {@link PersonaAiService} interface.
 */

const DISCLAIMER =
  "Generated by the Persona Studio mock service (deterministic, offline). This is a drafting aid, not research — validate everything against real sources before use.";

const SERVICE_NAME = `mock:${PROMPT_VERSION}`;

interface PatternSeed {
  theme: string;
  summary: string;
  archetype: string;
  tags: string[];
  needs: string[];
  frustrations: string[];
}

/**
 * A fixed behavioural pattern catalogue. Behaviour-first (never demographic).
 * Used to synthesise deterministic analysis and clusters.
 */
const PATTERN_CATALOGUE: PatternSeed[] = [
  {
    theme: "Time-pressed and efficiency-seeking",
    summary:
      "Participants describe tight schedules and expect low-effort, seamless logistics with minimal waiting.",
    archetype: "The Time-Pressed Guest",
    tags: ["efficiency-seeking", "low patience for friction", "planner"],
    needs: [
      "Fast, frictionless access and clear timing",
      "Predictable logistics they can plan around",
    ],
    frustrations: [
      "Waiting without information",
      "Unclear or last-minute changes",
    ],
  },
  {
    theme: "Recognition and status-oriented",
    summary:
      "Participants value being recognised and treated as important, and use the experience to signal status to others.",
    archetype: "The Status-Aware Host",
    tags: ["status-oriented", "relationship-builder", "host mindset"],
    needs: [
      "Visible recognition and premium treatment",
      "A setting that reflects well on them in front of guests",
    ],
    frustrations: [
      "Feeling like an anonymous number",
      "Generic, undifferentiated treatment",
    ],
  },
  {
    theme: "Authenticity and access-driven",
    summary:
      "Participants care about genuine, behind-the-scenes access and an authentic connection to the event.",
    archetype: "The Authenticity Seeker",
    tags: ["authenticity-driven", "curious", "experience-led"],
    needs: [
      "Privileged, authentic access to the moment",
      "Meaningful context and storytelling",
    ],
    frustrations: [
      "Feeling kept at arm's length",
      "Over-commercialised, staged experiences",
    ],
  },
  {
    theme: "Connection and shared-experience oriented",
    summary:
      "Participants prioritise time together and shared emotion over the details of the programme itself.",
    archetype: "The Connector",
    tags: ["relationship-first", "sociable", "memory-making"],
    needs: [
      "Comfortable space to spend time with their group",
      "Shared, memorable moments",
    ],
    frustrations: [
      "Rigid programmes that limit togetherness",
      "Environments too loud or rushed for conversation",
    ],
  },
];

function meta(): GenerationMeta {
  return {
    service: SERVICE_NAME,
    deterministic: true,
    disclaimer: DISCLAIMER,
    generatedAt: new Date().toISOString(),
  };
}

function excerptsFrom(text: string): string[] {
  const trimmed = text.trim();
  if (!trimmed) return [];
  return [trimmed.length > 160 ? `${trimmed.slice(0, 157)}…` : trimmed];
}

export class MockPersonaAiService implements PersonaAiService {
  async analyseResearchSources(
    input: AnalyseSourcesInput,
  ): Promise<SourceAnalysisResult> {
    const sourceIds = input.sources.map((s) => s.id);
    const supporting = input.sources.flatMap((s) =>
      excerptsFrom(s.extractedText),
    );

    const insights: SourceInsight[] = PATTERN_CATALOGUE.map((p, i) => ({
      id: `insight-${input.project.id}-${i}`,
      theme: p.theme,
      summary: p.summary,
      sourceIds,
      supportingExcerpts: supporting.slice(0, 2),
      frequency: sourceIds.length,
    }));

    return { meta: meta(), insights };
  }

  async generateBehaviouralClusters(
    input: GenerateClustersInput,
  ): Promise<ClusterSet> {
    const insights = input.analysis.insights;
    const count = clamp(
      input.desiredClusterCount ?? Math.min(4, Math.max(2, insights.length)),
      1,
      PATTERN_CATALOGUE.length,
    );

    const share = round2(1 / count);
    const clusters: BehaviouralCluster[] = [];
    for (let i = 0; i < count; i++) {
      const p = PATTERN_CATALOGUE[i % PATTERN_CATALOGUE.length];
      const insight = insights[i % Math.max(1, insights.length)];
      clusters.push({
        id: `cluster-${i}-${slug(p.archetype)}`,
        label: p.theme,
        summary: p.summary,
        suggestedArchetype: p.archetype,
        behaviouralTags: p.tags,
        needSignals: p.needs,
        frustrationSignals: p.frustrations,
        sourceIds: insight?.sourceIds ?? [],
        estimatedShare: share,
        confidence: "LOW",
      });
    }

    return { meta: meta(), clusters };
  }

  async generatePersonaFromCluster(
    input: GeneratePersonaInput,
  ): Promise<Persona> {
    const { cluster, project, template } = input;

    const persona = scaffoldPersona({
      projectId: project.id,
      template,
      family: project.family,
      name: `Draft: ${cluster.label}`,
      archetype: cluster.suggestedArchetype,
      category: cluster.label,
      oneLineEssence: cluster.summary,
      quote: draftedQuote(cluster),
      quoteType: "DRAFTED_HYPOTHESIS",
      confidenceLevel: "LOW",
      confidenceExplanation:
        "Machine-drafted from a behavioural cluster, not from field research. Every statement is an assumption or is pending validation.",
      behaviouralTags: cluster.behaviouralTags,
      sourceIds: cluster.sourceIds,
    });

    // Fill the scaffolded sections with clearly-labelled draft statements.
    const fill = (
      section: PersonaSection,
    ): PersonaSection => {
      const items = draftStatementsFor(section.key, cluster, section.id);
      return items.length > 0 ? { ...section, statements: items } : section;
    };

    return {
      ...persona,
      commonSections: persona.commonSections.map(fill),
      domainSections: persona.domainSections.map(fill),
    };
  }

  async auditPersona(persona: Persona): Promise<PersonaAuditResult> {
    return reviewPersona(persona);
  }
}

const NEED_KEYS = ["needs", "key_expectations", "expectations", "workplace_expectations"];
const FRUSTRATION_KEYS = ["frustrations", "pains"];
const BEHAVIOUR_KEYS = ["behaviours", "context"];
const ESSENCE_KEYS = ["essence"];

function draftStatementsFor(
  key: string,
  cluster: BehaviouralCluster,
  sectionId: string,
): PersonaStatement[] {
  const make = (
    content: string,
    idx: number,
    status: PersonaStatement["evidenceStatus"],
  ): PersonaStatement => ({
    id: `${sectionId}-draft-${idx}`,
    content,
    evidenceStatus: status,
    confidence: "LOW",
    sourceIds: [],
    editable: true,
  });

  if (ESSENCE_KEYS.includes(key)) {
    return [make(cluster.summary, 0, "ASSUMPTION")];
  }
  if (NEED_KEYS.includes(key)) {
    return cluster.needSignals.map((c, i) => make(c, i, "TO_VALIDATE"));
  }
  if (FRUSTRATION_KEYS.includes(key)) {
    return cluster.frustrationSignals.map((c, i) => make(c, i, "TO_VALIDATE"));
  }
  if (BEHAVIOUR_KEYS.includes(key)) {
    return cluster.behaviouralTags.map((c, i) =>
      make(`Tends to be ${c}.`, i, "ASSUMPTION"),
    );
  }
  return [];
}

function draftedQuote(cluster: BehaviouralCluster): string {
  const need = cluster.needSignals[0]?.toLowerCase() ?? "a seamless experience";
  return `What matters most to me is ${need}.`;
}

function slug(input: string): string {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function clamp(n: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, n));
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
