import type { PersonSeat } from "./schemas";

export const PEOPLE_SEATS: PersonSeat[] = [
  {
    id: "labs-manager-brazil",
    team: "Co-Design",
    costCenter: "HO202098",
    role: "Senior Service Designer / Sodexo Labs manager - BR",
    displayName: "Service Designer & SDX Labs manager - BR",
    kind: "internal",
    status: "pr1",
    category: "Manager & Expert Senior",
    location: "Brazil",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 146622,
    annualCostFromStart: 109966,
    opex: 109966,
    capex: 0,
    vacancyId: "1058",
    funding: "ACC",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "Validated to recruit. Starts P4-Dec.",
  },
  {
    id: "senior-sd-france",
    team: "Co-Design",
    costCenter: "NEW#FRTEAM",
    role: "Senior Service Designer",
    displayName: "Senior Service Designer",
    kind: "internal",
    status: "pr1",
    category: "Manager & Expert Senior",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 2,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 205066,
    annualCostFromStart: 187977,
    opex: 187977,
    capex: 0,
    vacancyId: "1080",
    funding: "ACC",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "Validated. Starts P2-Oct.",
  },
  {
    id: "arnaud-keravis",
    team: "Co-Design",
    costCenter: "HO202044",
    role: "VP design & lab",
    displayName: "Arnaud Keravis",
    kind: "internal",
    status: "pr0",
    category: "Director",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 346311,
    annualCostFromStart: 346311,
    opex: 346311,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "noel-kerjean",
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Head of Service and CoDesign",
    displayName: "Noel Kerjean",
    kind: "internal",
    status: "pr0",
    category: "Director",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 346311,
    annualCostFromStart: 346311,
    opex: 346311,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "diane-barbat",
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Junior Service designer",
    displayName: "Diane Barbat",
    kind: "internal",
    status: "pr0",
    category: "IT Specialist & Support",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 103893,
    annualCostFromStart: 103893,
    opex: 103893,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "trainee-sd-1",
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Trainee Service Design",
    displayName: "Trainee Service Design 1",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "trainee-sd-2",
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Trainee Service Design",
    displayName: "Trainee Service Design 2",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "labs-manager-west-us",
    team: "Co-Design",
    costCenter: "HO202100",
    role: "Senior Service Designer / Sodexo Labs manager - West US",
    displayName: "Service Designer & SDX Labs manager - West US",
    kind: "internal",
    status: "pr1",
    category: "Manager & Expert Senior",
    location: "US",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 275916,
    annualCostFromStart: 275916,
    opex: 275916,
    capex: 0,
    vacancyId: "1056",
    funding: "ACC",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "Validated to recruit. File still said Pr2.",
  },
  {
    id: "labs-manager-east-us",
    team: "Co-Design",
    costCenter: "HO202100",
    role: "Senior Service Designer / Sodexo Labs manager - East US",
    displayName: "Service Designer & SDX Labs manager - East US",
    kind: "internal",
    status: "pr2",
    category: "Manager & Expert Senior",
    location: "US",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 13,
    endPeriod: 13,
    days: null,
    theoreticalAnnualCost: 275916,
    annualCostFromStart: 0,
    opex: 0,
    capex: 0,
    vacancyId: "1057",
    funding: "ACC",
    inBudget: false,
    chainId: null,
    decisionId: null,
    notes: "Requested, not validated, not in budget.",
  },
  {
    id: "lead-pd-b2b",
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2B",
    displayName: "Lead Product Design B2B",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "Portugal",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 98993,
    annualCostFromStart: 74245,
    opex: 74245,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "File said Design System Manager after extern leave. Role is Lead Product Design.",
  },
  {
    id: "lead-pd-b2c-india",
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2C",
    displayName: "Lead Product Design B2C",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "India",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 60626,
    annualCostFromStart: 45470,
    opex: 45470,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    chainId: null,
    decisionId: "india-b2c-soeze",
    notes: "Part of the India B2C / SoEze budget decision.",
  },
  {
    id: "lead-pd-b2o",
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2O",
    displayName: "Lead Product Design B2O",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "Brazil",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 104705,
    annualCostFromStart: 78528,
    opex: 78528,
    capex: 0,
    vacancyId: "1081",
    funding: "BAU",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "File said Design System Manager after extern leave. Role is Lead Product Design.",
  },
  {
    id: "nicolas-duval",
    team: "Product design",
    costCenter: "HO001574",
    role: "Head of Product Design",
    displayName: "Nicolas Duval",
    kind: "internal",
    status: "pr0",
    category: "Manager & Expert Senior",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 205066,
    annualCostFromStart: 205066,
    opex: 205066,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "thomas-didier",
    team: "Product design",
    costCenter: "HO001574",
    role: "Apprentice",
    displayName: "Thomas Didier",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "dsm-internal-pt",
    team: "Product design",
    costCenter: "HO001574",
    role: "Design System Manager",
    displayName: "Design System Manager (internal)",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "Portugal",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 98993,
    annualCostFromStart: 74245,
    opex: 74245,
    capex: 0,
    vacancyId: "1055",
    funding: "BAU",
    inBudget: true,
    chainId: "design-system",
    decisionId: null,
    notes: "Replaces Ismael from P4-Dec. Not validated. Coverage hole if it stays Pr2.",
  },
  {
    id: "laura-geley",
    team: "B2B Platform",
    costCenter: "HO202019",
    role: "Lead Designer B2B",
    displayName: "Laura Geley",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "France",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 3,
    days: 65,
    theoreticalAnnualCost: null,
    annualCostFromStart: 45500,
    opex: 22750,
    capex: 22750,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "nikhil-soeze",
    team: "FM squad APMEA",
    costCenter: "HO202075",
    role: "Product Designer B2C Food Global (SoEze)",
    displayName: "TW - Nikhil",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "India",
    fte: 1,
    dailyRate: 500,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 59750,
    opex: 59750,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: "india-b2c-soeze",
    notes: "Full-time. File 0.5 was OPEX/CAPEX mix, not FTE. Cost kept from source.",
  },
  {
    id: "pedro-ciat",
    team: "MyApps (B2O Platform)",
    costCenter: "HO202021",
    role: "Senior Product Designer Lead",
    displayName: "CI&T - Pedro",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Brazil",
    fte: 1,
    dailyRate: 480,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 114720,
    opex: 57360,
    capex: 57360,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "jessica-ciat",
    team: "MyApps (B2O Platform)",
    costCenter: "HO202108",
    role: "UX Specialist SR, Design",
    displayName: "CI&T - Jessica",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Brazil",
    fte: 1,
    dailyRate: 376,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 89864,
    opex: 44932,
    capex: 44932,
    vacancyId: null,
    funding: "ACC",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "guillaume-sauvanon",
    team: "Product design",
    costCenter: "HO202085",
    role: "Design System PM / Product Designer",
    displayName: "Guillaume Sauvanon",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 600,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 1,
    days: 22,
    theoreticalAnnualCost: null,
    annualCostFromStart: 13200,
    opex: 6600,
    capex: 6600,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: "design-system",
    decisionId: null,
    notes: "Left September. Bridge until internalization.",
  },
  {
    id: "aron-vacancy",
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer B2B (Platform & Data Products)",
    displayName: "Vacancy - Aron",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 680,
    capexRatio: 0.5,
    startPeriod: 2,
    endPeriod: 11,
    days: 217,
    theoreticalAnnualCost: null,
    annualCostFromStart: 147560,
    opex: 73780,
    capex: 73780,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "External vacancy from P2-Oct.",
  },
  {
    id: "ismael-casado",
    team: "Product design",
    costCenter: "HO202085",
    role: "Design System Manager",
    displayName: "Ismael Casado",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Spain",
    fte: 1,
    dailyRate: 730,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 4,
    days: 88,
    theoreticalAnnualCost: null,
    annualCostFromStart: 64240,
    opex: 32120,
    capex: 32120,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: "design-system",
    decisionId: null,
    notes: "External bridge after Guillaume. Ends P4-Dec.",
  },
  {
    id: "javier-mora",
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer B2O Data / Power BI",
    displayName: "Javier Mora",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 167300,
    opex: 83650,
    capex: 83650,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "vacancy-ai-products",
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer New Products / AI products",
    displayName: "Vacancy - AI products",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 2,
    endPeriod: 11,
    days: 217,
    theoreticalAnnualCost: null,
    annualCostFromStart: 151900,
    opex: 75950,
    capex: 75950,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "External vacancy from P2-Oct.",
  },
  {
    id: "quentin-geiger",
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer B2C / Platform & FM / WRX",
    displayName: "Quentin Geiger",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 755,
    capexRatio: 0.5,
    startPeriod: 13,
    endPeriod: 13,
    days: 0,
    theoreticalAnnualCost: null,
    annualCostFromStart: 0,
    opex: 0,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: false,
    chainId: null,
    decisionId: null,
    notes: "Not in budget.",
  },
  {
    id: "michael-watzke",
    team: "Product design",
    costCenter: "HO202085",
    role: "Front end engineer for Design System",
    displayName: "Michael Watzke",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 590,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 141010,
    opex: 70505,
    capex: 70505,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    chainId: null,
    decisionId: null,
    notes: "Malt extension.",
  },
];
