import type { PersonSeat } from "./schemas";

export const PEOPLE_SEATS: PersonSeat[] = [
  {
    id: "nicolas-duval",
    lane: "management",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO001574",
    role: "Head of Product Design",
    displayName: "Nicolas Duval",
    kind: "internal",
    status: "pr0",
    category: "Manager & Expert Senior",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 205066,
    annualCostFromStart: 205066,
    opex: 205066,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "thomas-didier",
    lane: "management",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO001574",
    role: "Apprentice",
    displayName: "Thomas Didier",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 11,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "Finishes in July (P11).",
  },
  {
    id: "guillaume-sauvanon",
    lane: "design-system",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO202085",
    role: "Design System PM / Product Designer",
    displayName: "Guillaume Sauvanon",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 600,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 1,
    days: 22,
    theoreticalAnnualCost: null,
    annualCostFromStart: 13200,
    opex: 6600,
    capex: 6600,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: "design-system",
    decisionId: null,
    notes: "Left September. First cover in the Design System chain.",
  },
  {
    id: "ismael-casado",
    lane: "design-system",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO202085",
    role: "Design System Manager",
    displayName: "Ismael Casado",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Spain",
    fte: 1,
    dailyRate: 730,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 4,
    days: 88,
    theoreticalAnnualCost: null,
    annualCostFromStart: 64240,
    opex: 32120,
    capex: 32120,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: "design-system",
    decisionId: null,
    notes: "External bridge after Guillaume. Ends P4-Dec.",
  },
  {
    id: "michael-watzke",
    lane: "design-system",
    sortOrder: 2,
    team: "Product design",
    costCenter: "HO202085",
    role: "Front end engineer for Design System",
    displayName: "Michael Watzke",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 590,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 141010,
    opex: 70505,
    capex: 70505,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: "design-system",
    decisionId: null,
    notes: "Malt extension. Stays on the Design System squad.",
  },
  {
    id: "dsm-internal-pt",
    lane: "design-system",
    sortOrder: 3,
    team: "Product design",
    costCenter: "HO001574",
    role: "Design System Manager",
    displayName: "Design System Manager",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "Portugal",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 98993,
    annualCostFromStart: 74245,
    opex: 74245,
    capex: 0,
    vacancyId: "1055",
    funding: "BAU",
    inBudget: true,
    budgetGap: false,
    chainId: "design-system",
    decisionId: null,
    notes: "Takes over from Ismael in P4-Dec. Not validated. If this stays Pr2, Design System is uncovered after December.",
  },
  {
    id: "lead-pd-b2c",
    lane: "pd-b2c",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2C",
    displayName: "Lead Product Design B2C",
    kind: "internal",
    status: "pr1",
    category: "Expert",
    location: "India",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 60626,
    annualCostFromStart: 45470,
    opex: 45470,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: "india-b2c-soeze",
    notes: "Validated (Pr1). India B2C / SoEze budget can be realigned with Nikhil.",
  },
  {
    id: "aron",
    lane: "pd-b2c",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO202085",
    role: "Lead Product Design B2C (interim)",
    displayName: "Aron",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 680,
    capexRatio: 0.5,
    startPeriod: 2,
    endPeriod: 11,
    days: 217,
    theoreticalAnnualCost: null,
    annualCostFromStart: 147560,
    opex: 73780,
    capex: 73780,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "Named interim lead, not a vacancy. Starts P2-Oct.",
  },
  {
    id: "quentin-geiger",
    lane: "pd-b2c",
    sortOrder: 2,
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer B2C / Platform & FM / WRX",
    displayName: "Quentin Geiger",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 755,
    capexRatio: 0.5,
    startPeriod: 13,
    endPeriod: 13,
    days: 0,
    theoreticalAnnualCost: null,
    annualCostFromStart: 0,
    opex: 0,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: false,
    budgetGap: true,
    chainId: null,
    decisionId: null,
    notes: "Not in budget.",
  },
  {
    id: "nikhil-soeze",
    lane: "pd-b2c",
    sortOrder: 3,
    team: "Product design",
    costCenter: "HO202075",
    role: "Product Designer B2C Food Global (SoEze)",
    displayName: "TW - Nikhil",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "India",
    fte: 1,
    dailyRate: 500,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 59750,
    opex: 59750,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: "india-b2c-soeze",
    notes: "Already in. Full-time. File 0.5 was OPEX/CAPEX mix, not FTE.",
  },
  {
    id: "neha-b2c",
    lane: "pd-b2c",
    sortOrder: 4,
    team: "Product design",
    costCenter: "HO202075",
    role: "Product Designer B2C",
    displayName: "Neha",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "India",
    fte: 1,
    dailyRate: 450,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 107550,
    opex: 107550,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: "india-b2c-soeze",
    notes: "Already in on B2C. Full-time through P11-Jul at €450/day.",
  },
  {
    id: "laura-geley",
    lane: "pd-b2b",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO202019",
    role: "Lead Product Design B2B (interim)",
    displayName: "Laura Geley",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "France",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 3,
    days: 65,
    theoreticalAnnualCost: null,
    annualCostFromStart: 45500,
    opex: 22750,
    capex: 22750,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: "pd-b2b",
    decisionId: null,
    notes: "Interim lead through P3-Nov. After that the internal Lead is Pr2, with no budget.",
  },
  {
    id: "lead-pd-b2b",
    lane: "pd-b2b",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2B",
    displayName: "Lead Product Design B2B",
    kind: "internal",
    status: "pr2",
    category: "Expert",
    location: "Portugal",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 98993,
    annualCostFromStart: 0,
    opex: 0,
    capex: 0,
    vacancyId: null,
    funding: "BAU",
    inBudget: false,
    budgetGap: true,
    chainId: "pd-b2b",
    decisionId: null,
    notes: "Should take over from Laura in P4-Dec. Recruitment not validated and no budget. Coverage risk after November.",
  },
  {
    id: "lead-pd-b2o",
    lane: "pd-b2o",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO001574",
    role: "Lead Product Design B2O",
    displayName: "Lead Product Design B2O",
    kind: "internal",
    status: "pr1",
    category: "Expert",
    location: "Brazil",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 104705,
    annualCostFromStart: 78528,
    opex: 78528,
    capex: 0,
    vacancyId: "1081",
    funding: "BAU",
    inBudget: true,
    budgetGap: false,
    chainId: "pd-b2o",
    decisionId: null,
    notes: "Validated (Pr1). Internal lead for B2O.",
  },
  {
    id: "pedro-ciat",
    lane: "pd-b2o",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO202021",
    role: "Lead Product Design B2O (interim)",
    displayName: "CI&T - Pedro",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Brazil",
    fte: 1,
    dailyRate: 480,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 114720,
    opex: 57360,
    capex: 57360,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: "pd-b2o",
    decisionId: null,
    notes: "Interim lead until the internal Lead PD B2O is in.",
  },
  {
    id: "jessica-ciat",
    lane: "pd-b2o",
    sortOrder: 2,
    team: "Product design",
    costCenter: "HO202108",
    role: "UX Specialist SR, Design",
    displayName: "CI&T - Jessica",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Brazil",
    fte: 1,
    dailyRate: 376,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 89864,
    opex: 44932,
    capex: 44932,
    vacancyId: null,
    funding: "ACC",
    inBudget: true,
    budgetGap: false,
    chainId: "pd-b2o",
    decisionId: null,
    notes: null,
  },
  {
    id: "javier-mora",
    lane: "pd-data",
    sortOrder: 0,
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer B2O Data / Power BI",
    displayName: "Javier Mora",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 1,
    endPeriod: 11,
    days: 239,
    theoreticalAnnualCost: null,
    annualCostFromStart: 167300,
    opex: 83650,
    capex: 83650,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "vacancy-ai-products",
    lane: "pd-data",
    sortOrder: 1,
    team: "Product design",
    costCenter: "HO202085",
    role: "Product designer New Products / AI products",
    displayName: "Vacancy - AI products",
    kind: "external",
    status: "external",
    category: "Consultant",
    location: "Portugal",
    fte: 1,
    dailyRate: 700,
    capexRatio: 0.5,
    startPeriod: 2,
    endPeriod: 11,
    days: 217,
    theoreticalAnnualCost: null,
    annualCostFromStart: 151900,
    opex: 75950,
    capex: 75950,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "External vacancy from P2-Oct.",
  },
  {
    id: "gabriel-deroquefeuil",
    lane: "codesign",
    sortOrder: 0,
    team: "Co-Design",
    costCenter: "NEW#FRTEAM",
    role: "Senior Service Designer",
    displayName: "Gabriel DeRoquefeuil",
    kind: "internal",
    status: "pr0",
    category: "Manager & Expert Senior",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 205066,
    annualCostFromStart: 205066,
    opex: 205066,
    capex: 0,
    vacancyId: "1080",
    funding: "ACC",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "Already in since the beginning of September.",
  },
  {
    id: "arnaud-keravis",
    lane: "codesign",
    sortOrder: 1,
    team: "Co-Design",
    costCenter: "HO202044",
    role: "VP design & lab",
    displayName: "Arnaud Keravis",
    kind: "internal",
    status: "pr0",
    category: "Director",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 346311,
    annualCostFromStart: 346311,
    opex: 346311,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "noel-kerjean",
    lane: "codesign",
    sortOrder: 2,
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Head of Service and CoDesign",
    displayName: "Noel Kerjean",
    kind: "internal",
    status: "pr0",
    category: "Director",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 346311,
    annualCostFromStart: 346311,
    opex: 346311,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "diane-barbat",
    lane: "codesign",
    sortOrder: 3,
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Junior Service designer",
    displayName: "Diane Barbat",
    kind: "internal",
    status: "pr0",
    category: "IT Specialist & Support",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 103893,
    annualCostFromStart: 103893,
    opex: 103893,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "trainee-sd-1",
    lane: "codesign",
    sortOrder: 4,
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Trainee Service Design",
    displayName: "Trainee Service Design 1",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "trainee-sd-2",
    lane: "codesign",
    sortOrder: 5,
    team: "Co-Design",
    costCenter: "HO202044",
    role: "Trainee Service Design",
    displayName: "Trainee Service Design 2",
    kind: "internal",
    status: "pr0",
    category: "Intern/apprentice",
    location: "France",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 1,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 24737,
    annualCostFromStart: 24737,
    opex: 24737,
    capex: 0,
    vacancyId: null,
    funding: "BOOST",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: null,
  },
  {
    id: "labs-manager-west-us",
    lane: "codesign",
    sortOrder: 6,
    team: "Co-Design",
    costCenter: "HO202100",
    role: "Senior Service Designer / Sodexo Labs manager - West US",
    displayName: "Service Designer & SDX Labs manager - West US",
    kind: "internal",
    status: "pr1",
    category: "Manager & Expert Senior",
    location: "US",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 3,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 275916,
    annualCostFromStart: 229930,
    opex: 229930,
    capex: 0,
    vacancyId: "1056",
    funding: "ACC",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "Validated. Starts November (P3).",
  },
  {
    id: "labs-manager-brazil",
    lane: "codesign",
    sortOrder: 7,
    team: "Co-Design",
    costCenter: "HO202098",
    role: "Senior Service Designer / Sodexo Labs manager - BR",
    displayName: "Service Designer & SDX Labs manager - BR",
    kind: "internal",
    status: "pr1",
    category: "Manager & Expert Senior",
    location: "Brazil",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 4,
    endPeriod: 12,
    days: null,
    theoreticalAnnualCost: 146622,
    annualCostFromStart: 109966,
    opex: 109966,
    capex: 0,
    vacancyId: "1058",
    funding: "ACC",
    inBudget: true,
    budgetGap: false,
    chainId: null,
    decisionId: null,
    notes: "Validated to recruit. Starts P4-Dec.",
  },
  {
    id: "labs-manager-east-us",
    lane: "codesign",
    sortOrder: 8,
    team: "Co-Design",
    costCenter: "HO202100",
    role: "Senior Service Designer / Sodexo Labs manager - East US",
    displayName: "Service Designer & SDX Labs manager - East US",
    kind: "internal",
    status: "pr2",
    category: "Manager & Expert Senior",
    location: "US",
    fte: 1,
    dailyRate: null,
    capexRatio: 0,
    startPeriod: 13,
    endPeriod: 13,
    days: null,
    theoreticalAnnualCost: 275916,
    annualCostFromStart: 0,
    opex: 0,
    capex: 0,
    vacancyId: "1057",
    funding: "ACC",
    inBudget: false,
    budgetGap: true,
    chainId: null,
    decisionId: null,
    notes: "Requested, not validated, not in budget.",
  },
];
